### PR TITLE
[62] OpenAPI/Swagger in API module

### PR DESCRIPTION
**Pull request by jbonofre**

### CODE REVIEW

**Comment by jbonofre** [comment]
@swaroopar it's WIP for OpenAPI/Swagger UI integration. I will push new updates soon.

**Comment by jbonofre** [comment]
Here's the URL to get OpenAPI: http://localhost:8080/openapi

All good :) 

We can load the OpenAPI json in Swagger UI. I will add Swagger UI as optional module in the runtime.

**Comment by jbonofre** [comment]
Just added Swagger UI (via unpkg) on http://localhost:8080/swagger by default, loading OSC OpenAPI.

I will update the documentation now as part of this PR :)

**Comment by jbonofre** [comment]
Capture d’écran 2023-01-13 à 08 28 52

**Review by swaroopar — APPROVED** [review]

**Pull request merged**
